/**
 * @generated
 * Do not edit this file manually.
 */

import { RootState } from '@src/core'
import { TypedUseSelectorHook, useSelector } from 'react-redux'

export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
